name: publish slides to packages

on:
  push:
    tags:
      - 'sl.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: sample # Don't put filename extension.
    steps:
      - uses: actions/checkout@v2
      - name: build slide to pdf
        run: |
          npx @marp-team/marp-cli slides/$FILE_NAME.md --pdf
          npx @marp-team/marp-cli slides/${{env.FILE_NAME}}.md --pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: slides/${{env.FILE_NAME}}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}