name: publish slides to packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: sample # Don't put filename extension.
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo npm install -g @marp-team/marp-cli
      - name: build slide to pdf
        run: |
          sudo marp ./slides/${{env.FILE_NAME}}.md --pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: slides/${{env.FILE_NAME}}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}