name: publish slides to packages

on:
  push:
    tags:
      - 'sl.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: sample # Don't put filename extension.
    steps:
      - uses: actions/checkout@v2
      - name: build slide to pdf
        run: |
          docker run --rm -u root --init -v "$(pwd):/home/marp/app"
          -e LANG="ja_JP.UTF-8" marpteam/marp-cli slides/${{env.FILE_NAME}}.md
          --pdf
          -o slides/${env.FILE_NAME}.pdf
          --allow-local-files
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: slides/${{env.FILE_NAME}}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}