name: publish slides to packages

on:
  push:
    tags:
      'sl.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: how-to-use-git-and-github.md # Don't put filename extension.
    steps:
      - uses: actions/checkout@v2
      - name: Install font
        run: sudo apt install fonts-noto
      - name: Install dependencies
        run: sudo npm install -g @marp-team/marp-cli
      - name: build slide to pdf
        run: |
          marp ./slides/${{env.FILE_NAME}}.md
          --pdf
          --allow-local-files
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: slides/${{env.FILE_NAME}}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}